name: Creative
version: 1.0.0-SNAPSHOT
main: pl.trollcraft.crv.CreativePlugin

api-version: 1.16

author: 'Jakub Zelmanowicz'

load: POSTWORLD

depend: [PlaceholderAPI, Multiverse-Core, Vault]

commands:
  prefix:
    description: Opens a prefixes MENU.
  prefixadmin:
    description: Prefixes admin management command.

  games:
    aliases: [gra, gry, game]
    description: Games command.
  parkour:
    aliases: [par]
    description: Parkour editing command.

  creative-vehicles-remove:
    aliases: [cvr, cvrem]
    description: Removes all vehicles or vehicles which belong to a certain payer.

  vehicles:
    aliases: [pojazdy, poj]
    description: Opens Vehicles Shop.

  locateVehicle:
    aliases: [gdziePojazd, gdpoj]
    description: Locates vehicles for specific player.

  clear:
    aliases: [clr]
    description: Removes specific items from inventory.